camicroscope/caMicroscope

- api/Configuration/config.php
- api/Data/getAnnotSpatialLymph.php
Change the API name to postAlgorithmForImageLymph
> Fix duplicate postAlgorithmForImage API name conflict

- js/annotationtoolslymph/ToolBar_Lymph.js
- js/annotationtoolslymph/osdAnnotationTools_Lymph.js
Preselected the lymphocyte algorithms
> Lymphocyte patch 1

- api/Data/lymphocyteData.php
Removed hardcoded api keys from lymhocyteData.php
> Removed hardcoded api keys from lymhocyteData.php

- osdCamicroscope_Lymph.php
Fixed zoom in and zoom out on scroll for the caMic Lymphocyte App
> Fixed zoom in and zoom out on scroll for the caMic Lymphocyte App

- js/Helpers/OsdStateManager.js
- osdCamicroscope.php
- osdCamicroscope_Lymph.php
- osdCamicroscope_sc.php
This is a fix to a reported bug. waiting for confirm on testing on another instance
> Delay State Generation to Avoid OSD Conflict

- js/Helpers/StateManager.js
- js/Helpers/StateSchema.js
- js/annotationtools/ToolBar.js
- osdCamicroscope.php
doesn't clog history, flexible schema, does post to url bar
> New state manager

- api/Configuration/config.php
- osdCamicroscope.php
- osdCamicroscope_Lymph.php
- osdCamicroscope_sc.php
quick fix for #87 
Is this already done in another branch staged for release? If so, ignore.
> Relative path

- js/Helpers/StateSchema.js
- js/annotationtools/ToolBar.js
- js/annotationtools/osdAnnotationTools.js
- osdCamicroscope.php
- shared/ToolBar.js
I don't know how to test your applications, but this should hopefully undo the changes which were part of sidesplit.
> revert sidesplit and selections as class obj

- js/Helpers/session_notify.js
this should prevent the 401. I don't know what's going on with the json encoding issue, so if I figure out, I may further extend.
> change to match file change in security

- shared/ToolBar.js
> Port 8080 and folder html2 had been removed

- js/annotationtoolslymph/ToolBar_Lymph.js
- osdCamicroscope_Lymph.php
Switcher fixed.  Panel comes up now.  Fixes bug #251
> Fixed Superuser in Lymphocyes Bug #251

- js/annotationtools/geoJSONHandler.js
> PR: bug #207

- js/annotationtools/osdAnnotationTools.js
> hotfix 278

- apps/lite/segment/segment.js
- apps/lite/viewer/uicallbacks.js
- apps/viewer/uicallbacks.js
- common/pureform/pure-form.css
- common/util.js
- core/extension/openseadragon-canvas-draw-overlay.js
- Require polygons not to self intersect
- Add back and bug report buttons to segmentation application
> Simple Polygon Restriction

- apps/lite/viewer/uicallbacks.js
- apps/viewer/uicallbacks.js
- core/extension/openseadragon-overlays-manage.js
2. redraw annotations on resize event.
> sidesplit - sync motion and redraw on resize

- apps/landing/landing.html
> Fixed spelling :)

- apps/loader/chunked_upload.js
- apps/loader/loader.html
- apps/loader/loader.js
1. Status bar displays JSON as a table for better readability.
2. Thumbnail only displayed for 'Check'
> Minor UI Changes

- apps/viewer/init.js
> simplify store

- apps/model/model.js
- apps/segment/segment.js
- apps/segment/segmentpanel/segmentpanel.css
- apps/segment/segmentpanel/segmentpanel.js
Allow to choose from pixel normalization, centering and standardization
> Allow to select image preprocessing method

- apps/model/model.js
Spelling of "please" was wrong in model section.
> Spelling correction of please

- apps/table.html
> impoving the instructions in #226

- apps/table.html
closes https://github.com/camicroscope/caMicroscope/issues/229
> Added search bar and sorting buttons.

- apps/segment/segmentpanel/segmentpanel.js
Added title to close button in segment panel. Now when we hover to close button, we would see a text displayed "Close Panel"
> Added title to button

- docs/README.md
Updated toolbar shortcuts in docs
> document toolbar shortcuts

- apps/model/model.html
- apps/model/model.js
- apps/segment/segment.js
Earlier, class list once made can't be altered. This caused the following problems:
- There may be some spelling errors needed to be fixed.
- We may need to add some more classes
- We may need to remove some classes
So I added this functionality.
The new info modal box looks like:
Then a modal box is displayed to take input 
Then a message is displayed upon success. 
And the changes are saved
> Feature to change class list

- apps/table.html
After uploadin the the uploaded slide is not reflected in the table unless the user refreshes page.
A small fix for that by initialzing table on form exit.
Now after closing form the uploaded slide is reflected.
> Initialize on form exit

- apps/table.html
Icons are added in the upload and reload button using fontawesome.
>  Button Icons addition 

- .eslintrc.js
- apps/model/model.js
- apps/segment/segment.js
Fixes a sub-issue of #274
I have made sure that the application works, as earlier.
@birm , please review.
> Removed 'ignore no-extra-bind' in ESLint configuration

- .eslintrc.js
- apps/loader/chunked_upload.js
Fixes a subissue of #274
I have made sure that the application works, as earlier.
@birm , please review.
> Removed 'ignore prefer-promise-reject-errors' in ESLint configuration

- apps/heatmap/init.js
- apps/labeling/labeling.js
- apps/viewer/init.js
- common/util.js
- demo/demo.js
@birm I found an interesting bug here
https://github.com/camicroscope/caMicroscope/blob/75561aff1c5c259b502774da8566e9e3d2d92318/apps/viewer/init.js#L1148
The setInterval runs atleast once before checking the conditions inside. It was causing exacly on second of delay after clicking on home button. 
After the fix it will redirect instantly.
> Redirect bug fix

- apps/heatmap/init.js
- apps/labeling/labeling.js
- apps/viewer/init.js
- common/util.js
- demo/demo.js
Hey @birm, I forgot to add theses to #284, Whithout these the page will not redirect to home after 5s. I am really sorry for that.
Thanks
> Additional fixes to #284

- apps/landing/landing.html
- apps/landing/main.css
- apps/signup/signup.css
- apps/signup/signup.html
- apps/table.css
- apps/table.html
1. Active Section can now be clearly identified.
2. Hover effect on nav bar items.
3. Icons are added to the nav bar items.
> Nav-bar hover effect (with active page indicator) and icons addition

- apps/table.html
File extension will be validated at client side also. Users will get feedback message as following.
Some in the slack group are saying that SlideLoader file extension validation is failing. So, just to be safe and also to improve user experience.
> Client side file extension validaion

- components/toolbar/toolbar.js
Fixes #296 
Now, it works perfectly :
> Fixed magnifier

- apps/viewer/popup.css
- apps/viewer/uicallbacks.js
- apps/viewer/viewer.html
The popup message display : 'For more options, right click anywhere on image'
Fixes [Issue-110](https://github.com/camicroscope/Distro/issues/110) of Distro repository.
Now, whenever user select 'Draw annotation' tool, he sees a popup message, for about 3 seconds, telling him to 'right-click anywhere on the image, for more options'.
Screencast -
> Added popup message, when user opens draw annotation tool [Enhancement]

- apps/loader/loader.js
Fixes #305 
Now, it looks like -
> Made check slide table responsive in upload slide modal [ FIX #305 ]

- common/util.js
The code in 'util.js' was not compiling. This would fix it. 
Also, the travis build was failing earlier. This will make it pass.
> Change 'reutrn' to 'return' and fix lint issues

- apps/table.html
The page indicator will only be visible when the number of pages are greater than 1.
No indicator will be shown if there is only 1 page.
> Table Pagination Visibility

- apps/Info.html
- apps/info.css
- apps/table.html
- core/Store.js
Fixes https://github.com/camicroscope/Distro/issues/95
This is an initial implementation of the Information Dashboard.
**Few Ideas**
Clicking on each slide in the table could open a popup with all the summary related to the slide.
@birm Please suggest what else to include.
> Initial Implementation of Information Dashboard

- apps/loader/loader.js
- apps/table.css
- apps/table.html
A download button is added in the slides table which the user to download the slide image.
This is used with [SlideLoader #26](https://github.com/camicroscope/SlideLoader/pull/26)
> Download button in the slides table

- apps/model/model.js
- apps/segment/segment.css
The style update was already present in the model upload box so it should be in the segment upload box too. Model summary description was not present in the help section.
> Added model summary to help button and style update in segment

- apps/model/model.css
- apps/model/model.html
- apps/model/model.js
- apps/segment/segment.css
- apps/segment/segment.js
Minor UI changes in info modal box of model app.
> Minor UI changes in model app

- apps/Info.html
- apps/info.css
Initial Implementation of Details button in Information Dashboard
- This is the implementation of details button in information dashboard as this was mentioned in my initial implementation(#323 ) of dashboard for later.
> Added Details button in Information Dashboard

- apps/table.js
- package.json
* add linting to table.js
* try to mitigate unsafe html rendering which is all over table.js
While using document.createElement and related would be best, this would have taken to long, so after I gave up on that, I just used the sanitize function made earlier.
> Safe html in table

- apps/Info.html
- apps/dev-workbench/createAlgo/bench.css
- apps/dev-workbench/createAlgo/bench.html
- apps/dev-workbench/workbench.css
- apps/dev-workbench/workbench.html
- apps/dev-workbench/workbench.js
- apps/landing/landing.html
- apps/table.html
~~This works with [Caracal #38](https://github.com/camicroscope/Caracal/pull/38)~~
This works with [SlideLoader #32](https://github.com/camicroscope/SlideLoader/pull/32)
1. Stepper interface is used so that it's easy for the user to navigate sequentially.
2. Initial implementation of dataset selection has been shown where user can either choose a pre-made (formatted i.e spritesheet & labels) dataset or can create an own dataset from labelling files from caMircoscope. 
3. When creating own dataset user can choose which label images to use. No of images under every label is shown and user can select which of them to keep.
4. The user will be returned with a zip file containing the spritesheet and binary labelling according to the selection.
5. The corresponding zip file can then be browsed …
> Initial Design/Workflow for Development Workbench + Initial implementation of Spritesheet generator.

- css/style.css
closes #431
Draft, since it's super minimal and I don't like using !important.
The below was taken on a simulated 3500 px wide monitor
> Use vw for toolbar button sizes

- apps/dev-workbench/createAlgo/bench.html
- apps/dev-workbench/createAlgo/bench.js
- apps/dev-workbench/readme.md
- apps/dev-workbench/workbench.html
- apps/dev-workbench/workbench.js
- Users can now export their work as a zip file to continue later on
- Importing file can restore the dataset, layer details, parameters which were saved during export.
- A user guide for the Workbench is provided into `readme.md`
Tested on Firefox (79.0), Chrome (84.0), Brave (1.11.x) on Windows 10 and Linux-LTS (arch - deepin)
> Import/Export feature and user guide [Development Workbench]

- apps/dev-workbench/createAlgo/bench.css
- apps/dev-workbench/createAlgo/bench.html
- apps/dev-workbench/createAlgo/bench.js
- apps/dev-workbench/createAlgo/utils/data.js
- apps/dev-workbench/workbench.css
- apps/dev-workbench/workbench.html
- apps/dev-workbench/workbench.js
- A button to reset/delete all hidden layers has been added in the layers editor.
- Comments for relevant functions have been added in the codebase.
- Some css shifted to external from inline
- Some cleaning.
> Reset Layers Button, in-code comments & css to external [Development Workbench]

- apps/model/README.md
> Update demo video link in readme

- apps/dev-workbench/createAlgo/bench.js
- apps/dev-workbench/readme.md
This is a small change which fixes a minor corner case issue during importing in step 2 and a youtube demo video's link containing development workbench in action is added to user guide.
> Import fix and demo video link into user guide [Development Workbench]

- HISTORY.md
- apps/model/model.js
- test/ui/operationpanel-test-cases.js
> Bugfix: Model Failed to read coordinates

- HISTORY.md
- apps/model/model.js
- apps/segment/segment.js
Fix error using a model over the selected region #453
Changes made on the segment.js and model.js files to properly read the coordinates of the segmentations.
https://github.com/camicroscope/caMicroscope/issues/453
Test the code by loading different segmentation and classification models into the system, comparing the result with the one shown in the demo on the caMicroscope page.
- [ X ] Bug fix (non-breaking change which fixes an issue)
- [ X ] My code follows the code style of this project.
> Coordinate System Fix

- apps/model/model.js
When changing the class list in model app, we needed to rewrite complete list of classes even if we wanted to change even one class. This PR fixes this problem.
Makes editing class easier
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
> Edit class list default value

- apps/signup/signup.css
- apps/signup/signup.html
- apps/signup/signup.js
> Add Login Button to Signup

- apps/Info.html
- apps/info.css
- apps/landing/landing.html
- apps/table.css
- apps/table.html
> Improve Table UI

- apps/loader/chunked_upload.js
- apps/loader/loader.js
- apps/table.html
- apps/table.js
- The upload process has been made easy for the end user.
- Number of steps (button clicks) for the end user has been reduced.
- Previously, there was a bug in which the file upload progress was shown incorrectly. The bug is now fixed.
- A user-friendly progress bar with live file upload progress has been added.
- The backend has not been altered.
- Previous upload process seemed to be a little cumbersome for the end user.
- Browser: Firefox (v83), Chromium (v87)
- OS: Windows 10, Arch KDE (Linux-LTS)
> Updated upload process [Enhancement]

- apps/table.js
- common/util.js
- core/Store.js
- core/Validation.js
Fixes #465
I'm not yet sure of any knock-on effects, so I'm testing. Of course, I want @nanli-emory / @JasoxLee to yell at me if this is a bad change :smiley_cat:
> hotfix for annots without shape

- apps/table.html
- apps/table.js
- Typo in update name, `followingdetails` --> `following details`
- Slide-Table layout changed(stretched) as before, Change Introduced due to [#477](https://github.com/camicroscope/caMicroscope/pull/477#issue-556406397)
> Minor UI and typo fix

- README.md
- Added slack and mailing list info in the readme
- Added links for contribution and structure to make it beginner friendly
Inspired from other repos like [Julia](https://github.com/JuliaLang/julia)
> Improvements in Readme

- apps/heatmap/heatmap.html
- apps/labeling/labeling.html
- apps/model/model.html
- apps/segment/segment.html
- components/toolbar/toolbar.js
Fixes for Commit: [`9fe44b1`](https://github.com/camicroscope/caMicroscope/commit/9fe44b1e1a35802f1d85db549c0ae2aa34a39862)
- Toolbar tippy fix
- Tour fix
> quickfixes

- .github/workflows/node.js.yml
- apps/viewer/init.js
Travis CI is a little less reliable, may as well try to keep things in github
> Github action for ci testing

- apps/batchloader/batchLoader.js
- components/heatmapcontrol/heatmapcontrol.js
- Improved in-code documentation to heatmapcontrol.js and batchloader.js 
- If it fixes an open issue, please link to the issue here.
- helps in #413 
**Please describe in detail how you tested your changes.
- Doesn't affect code
> Improve HeatmapControl and batchLoader Documentation

- HISTORY.md
- apps/viewer/init.js
The link for the additional links feature was only working on localhost:4010 deployments.
Made this more robust, also added "append slide" mode
> Bugfix: Additional Links Error

- apps/landing/landing.html
- apps/landing/main.css
- apps/signup/signup.css
- apps/signup/signup.html
Issue: #517
I have updated the version of bootstrap from 4.4.1 to 5.0.0. 
The latest version of bootstrap is 5.0.0 and caMicrscope currently uses 4.4.1. 
I also worked on improvement in the responsiveness of the application for the smaller screens. I added a few css styles to make the UI more attractive.
UI:
Desktop:
I PhoneX
Sign-Up page:
Smal screens:
> Updated to bootstrap@5

- apps/crossviewer/crossviewer.html
- apps/crossviewer/dataloaders.js
- apps/crossviewer/init.js
- apps/crossviewer/uicallbacks.js
- apps/viewer/init.js
- apps/viewer/tut.js
- apps/viewer/uicallbacks.js
- apps/viewer/viewer.html
- components/crossmenu/crossmenu.css
- components/crossmenu/crossmenu.js
- components/simplecontextmenu/simplecontextmenu.js
- components/spyglass/spyglass.js
- components/toolbar/toolbar.css
- components/toolbar/toolbar.js
In this milestone I have implemented the options for choosing which slide to view in the viewer page and have implemented pagination, sorting and filtering as was discussed with @nanli-emory. In the cross viewer I have implemented independent panning, zooming, adding labels, adding rulers, adding annotations , viewing layer managers for both the slides. using magnifier tool and the screenshot feature which takes screenshot of both the slides and joins them together. 
This is the first Milestone of my GSoC Project Cross Slide Coordinated Viewing.
I have tested this feature in Google Chrome and Firefox and everything seems to be working fine.
> GSoC Project Cross Slide Coordinated Viewing First Milestone

- apps/viewer/uicallbacks.js
- common/enhance.js
- common/smartpen/autoalign.js
- core/extension/openseadragon-canvas-draw-overlay.js
Moving points - Milestone 2
- Moving-points feature - an annotation extension
I have added a general annotation utility of moving points in which the user can drag annotation after drawing it. I tested it, it works well in all scenarios (zoom, shape) (with smartpen as well).
Currently, only the draw tool utilizes this feature. 
It's easier for users to drag and get perfect annotations than drawing it.
Added in `openseadragon-canvas-draw-overlay` (in the startDrawing, Drawing, __endNewfeature, misc functions)
[My blog](https://rohanmallick.wordpress.com/2021/06/28/moving-points-enhance/)
Feel free to provide suggestions, improvements, contributions. And please review
> Moving points

- apps/crossviewer/dataloaders.js
- apps/crossviewer/init.js
- apps/crossviewer/uicallbacks.js
- apps/viewer/uicallbacks.js
- common/util.js
- components/crossmenu/crossmenu.js
- components/layersviewer/layersviewer.css
- components/layersviewer/layersviewer.js
- components/spyglass/spyglass.js
- components/toolbar/toolbar.js
- core/extension/openseadragon-measurement-tool/openseadragon-measurement-tool.js
- core/extension/openseadragon-zoom-control/openseadragon-zoom-control.js
- package.json
Basic slide sync feature added. Adding rulers to screenshot feature extended to crossviewer. Rotation support added while adding rulers. All new js files are lint fixed.
This is in continuation to my previous PR #527
I tested this on my local development setup
> Second Milestone : Cross Slide Coordinated viewing

- apps/crossviewer/crossviewer.html
- apps/crossviewer/init.js
- apps/crossviewer/tut.js
- apps/crossviewer/uicallbacks.js
- common/util.js
- components/layersviewer/layersviewer.css
- components/layersviewer/layersviewer.js
- core/extension/openseadragon-canvas-draw-overlay.js
- core/extension/openseadragon-overlays-manage.js
- core/extension/osd-heatmap-overlay.js
- core/openseadragon-imaginghelper.min.js
- core/openseadragon-scalebar.js
* Added rotation support for viewing heatmaps and annotations.
* Added rotation support to slide sync.
* Added rotation support in Slide Capture
* Added tutorial in cross slide viewer.
Tested the features in my local development environment
**Browser** : Google Chrome
**OS** : Linux
* Slide Capture on rotated slides with heatmaps and annotations
* View recording of the features [here](https://drive.google.com/file/d/1HOp25TqShKJHoUminQwtQP6A_vfmbbfW/view?usp=sharing)
> Third Milestone : Cross Slide Coordinated Viewing

- HISTORY.md
- apps/viewer/init.js
- apps/viewer/viewer.html
- common/PathdbMods.js
* fix pathdb compatible human readable slide urls
> For 3.9.10

- apps/MicroRT-view/automation.html
- apps/MicroRT-view/automation.js
- apps/MicroRT-view/automation_style.css
- apps/MicroRT-view/init.js
- apps/MicroRT-view/microRT.css
- apps/MicroRT-view/microRT.html
- apps/table.js
Added MicroRTview Button in table.js file
> Added MicroRTview button

- core/CaMic.js
* Bugfix for Magnifying glass with slide token auth
> For 3.10.1

- apps/dev-workbench/workbench.css
- apps/dev-workbench/workbench.html
> Fixed Workbench Navbar Overlapping 

- apps/port/export.html
Just Styled the app/port/export.html
Before when we were going to export.html it felt like we were not anymore in the caMicroscope web application we came somewhere else. So, I just gave the color code and style which the website follows. 
##Before :
##After :
This, is my first pull request to caMicroscope @birm so, please accept it 🥺 and let me know if somethings more to change in this issue.
> Styled export.html 

- apps/dev-workbench/workbench.css
- apps/dev-workbench/workbench.html
- apps/table.css
- apps/table.html
- package-lock.json
Fixes issue no: #602 
The bug has been fixed
Thank you. Do let me know if there are any changes to make.
> Fixed reload button

- apps/port/import.html
Fixed issue no. #607 
The user interface of the import.html has been updated
Earlier the site looked something like this:
Now, it has been made similar to that of the whole website:
Thank you. Do let me know if there are any changes to make.
> Fixed import.html interface

- core/CaMic.js
This code will also be used for bioformats
> Naming only: refer to iipsrv instead of openslide to prevent confusion

- apps/dev-workbench/workbench.html
This Pull Request adjusts the card’s position in the workbench step-1 and enhances their responsiveness.
Before changes ::
After changes ::
https://github.com/camicroscope/caMicroscope/assets/124369508/694ca031-649e-4e27-af33-839c08152386
> PR to adjust the card’s position and responsiveness. 

- apps/Info.html
- apps/signup/signup.html
- apps/table.html
- common/footer.js
* Created common/footer.js
* Removed static text and added a placeholder for copyright text in apps/signup/signup.html, apps/Info.html, and apps/table.html
* Replaced the <p> tag containing the date with place holders with unique ids
* Wrote JQuery script (footer.js) to populate the placeholder with the current year
This is an attempt to ensure that dates in all  footers are consistent with the current year. #760
> modified date in footer to reflect the current year

- apps/signup/signup.html
Add a gap between Signup and Feedback buttons.
From
To
Refine the UI to ensure elegance and consistency with the style of existing buttons.
Yes. Tests passed.
> add gap between Signup and Feedback buttons

- apps/table.css
- apps/table.html
Solved - Issue #762 Unclear step in "Upload New Slide" dialog
Solved the ambiguity in the 3rd step. Also added the definition for the css class "close" applied on the &times; modal closing button.
> Solved - Issue #762 Unclear step in "Upload New Slide" dialog

- apps/segment/segment.css
Improved error message visibility in the segment model upload interface by changing the font color from yellow to red for enhanced clarity and user experience.
This change addresses the difficulty of reading error messages due to insufficient contrast with the background color.
I've updated the error message color to red to increase visibility, although I'm open to feedback if this may not be the best choice.
> Improved error message visibility in the segment model upload interface

- apps/table.css
Fixed issue #737
Reload button margin needed in slides page(table.html) #737
Hello  Gbenga Oluwadahunsii,
I hope this message finds you well. I wanted to reach out to express my interest in contributing to the caMicroscope project. As an Outreachy applicant, I am eager to contribute to open-source projects, and I noticed that there is an open issue titled "Reload button margin needed in slides page (table.html) #737" that I believe I can help with.
I have already fixed the issue in my local repository and would like to contribute this fix to the project. Could you please guide me on the next steps to create a pull request and get my changes reviewed and merged?
Thank you for your time and consideration. I look forward to contributing to the caMicroscope project.
Best regards,
Ayesha …
> Fixed issue #737

- apps/Info.html
- apps/common.css
- apps/landing/landing.html
- apps/signup/signup.html
- apps/table.html
- common/util.js
I’ve recently created a reusable footer component and integrated it into various parts of our application, including the **signup**, **table**, **info**, and **landing page**. I’ve also cleaned up unused code in the landing page header.
**before:**
**after:** 
The primary motivation behind this update was to enhance consistency and maintainability across different sections of our application. By using a reusable footer, we ensure a uniform look and feel, which improves the overall user experience.
I have created a footer util, which would be reused in all the components we would need. And since we have a common file, I have included it in the utils in the common folder and included the CSS in the common.css file. 
I did import the scripts and called the function "insertFooter()" to invoke …
> Reusable footer component integration and Code cleanup

- apps/landing/landing.html
- apps/landing/main.css
Adding a loading animation on window load
Built with html nad pure css
Whenever it took time to load it always showed a blank white screen hence I added loader to it
https://github.com/camicroscope/caMicroscope/assets/87171143/2584daad-9a62-4427-85c5-c9a8dab73c49
> Adding a loader

- apps/signup/signup.html
Updated the signup page to improve user experience by repositioning the signup button above the "Already have an account?" text and ensuring consistency in the navbar design with the landing page.
The current signup button placement and navbar inconsistency were identified as potential issues impacting user experience. This Pull Request addresses these concerns to streamline the signup process and maintain visual consistency across pages.
No specific questions at the moment. Feedback and suggestions are welcome.
> Improve signup page user experience and consistency

- apps/dev-workbench/workbench.html
Summary
The type="text/javascript" attribute has been removed from the script tags in the HTML code. This change aligns with the recommendation from the W3C, which states that the type attribute is unnecessary for JavaScript resources  By removing this attribute, the HTML code becomes cleaner and more compliant with modern web standards.
Motivation
The motivation behind removing the type="text/javascript" attribute is to adhere to current best practices and recommendations set forth by the W3C. This change ensures that the HTML code is more concise, easier to maintain, and aligns with industry standards for web development.
According to the W3C recommendation, the type="text/javascript" attribute is not necessary for JavaScript resources in HTML documents. Thus, removing this attribute …
> Removed unnecessary attrubutes

- apps/table.css
- apps/table.html
Summary
The changes involved updating the outdated cellspacing, cellpadding, and align attributes of the table to modern CSS properties and values. Instead of using these attributes, CSS properties such as padding, border-spacing, and text-align were utilized to achieve the desired layout and alignment.
Motivation
The motivation behind this adjustment is to adhere to modern web development best practices and standards. The use of CSS for styling provides more flexibility, maintainability, and compatibility across different devices and browsers. By transitioning away from deprecated HTML attributes to CSS properties, the codebase becomes more future-proof and easier to maintain.
Testing
The changes have been thoroughly tested across various browsers and devices to ensure consistent …
> Table html page adjusted to W3C standards

- apps/port/import.html
Summary
I added the rel attribute to the CSS link tag and moved the styles tag from between the head and body tags to the head tag. This ensures better adherence to HTML standards and improves the organization of the document structure.
Motivation
The motivation behind these changes is to ensure that the HTML document follows best practices and standards recommended by the W3C. Adding the rel attribute to the CSS link tag helps define the relationship between the current document and the linked resource, enhancing the document's semantics. Moving the styles tag to the head section ensures that styles are loaded before the content, which can improve the rendering performance of the page.
Testing
These changes have been tested by validating the HTML document using online validators such as …
> Importhtml : W3C standards

- apps/user/user.css
- apps/user/user.html
Summary
In this pull request, I made several changes to improve the HTML document:
Removed the obsolete width attribute from the table tag and included the width property in CSS for better styling control.
Removed the aria-describedby attribute from the input tag since it is not referenced anywhere in the document.
Removed the charset=utf-8 declaration, as most modern browsers default to UTF-8 encoding.
Moved stray script tags from within the body tags to ensure compliance with HTML standards.
Motivation
The motivation behind these changes is to ensure that the HTML document adheres to current best practices and standards. By removing obsolete attributes and organizing the document structure properly, we improve maintainability, readability, and compatibility across different browsers and …
> Update : W3C standards

- components/toolbar/toolbar.css
- components/toolbar/toolbar.js
The pop up on the toolbar was not efficient and it blocked other components while displaying the title of the tool. Hence modified it, making it more user friendly
Below is the changes, I changed the background color to dark as it would be easier to read and made sure that the title is not overlapping with other components and removed the default title pop up.
https://github.com/camicroscope/caMicroscope/assets/87171143/23c577b2-31f1-4c2b-8e2a-d47a270afa41
https://github.com/camicroscope/caMicroscope/assets/87171143/41add129-f3c0-4e7a-8e1b-207919a3337b
If there are any questions or suggestions do feel free to comment down below
> Modifying toolbar title

- apps/port/import.css
- apps/port/import.html
- apps/port/style.css
In this pull request, I made several changes to improve the responsiveness and organization of the webpage:
- Created a separate CSS file for the import form to organize the styling better.
- Removed unused CDN CSS to improve webpage speed and performance.
- Enhanced the appearance of the form to make it more appealing.
- Centralized CSS for potential future improvements and easier maintenance.
- Implemented responsive design principles to ensure the page adapts well to different screen sizes.
- Noted that the form now complies with Human-Computer Interaction (HCI) and Web Content Accessibility (WCA) standards for improved accessibility and usability.
The motivation behind these changes is to create a more user-friendly and efficient webpage. By separating the CSS for the import form and …
> WCA Standards : Enhancing Import Page Responsiveness and Struture

- apps/signup/signup.css
- apps/signup/signup.html
- apps/signup/signup.js
adjusted the email signup validation error
I adjusted the email signup validation which was in alert before I changed it to an inline error  validation
Yes, this pull request fixes open issues
yes, it has been tested 
##before fixing 
##After fixing
> adjusted the email signup validation error

- apps/Info.html
- apps/landing/landing.html
- apps/signup/signup.html
- apps/table.html
**Title: Improved Mobile-Friendly Navigation Bar**
This pull request addresses the lack of mobile-friendly design elements, particularly in the navigation bar, on the current website. It ensures a responsive design that accommodates different screen sizes and enhances user experience on mobile devices. The fix adheres to Human-Computer Interaction (HCI) and Web Content Accessibility (WCA) standards, improving accessibility rates.
The current navigation bar collapses into a single button on mobile devices, making it difficult for users with larger fingers to navigate efficiently. This update aims to improve accessibility and usability by providing a more user-friendly experience on mobile devices, aligning with HCI and WCA standards.
Testing has been performed on various devices and …
> Issue Fixed #745 : Accessibility (WCA) standards

- apps/heatmap/heatmap.html
Summary
I made the following changes to improve compliance with W3C standards:
Removed the unnecessary type attribute from <script> tags.
Moved a  <script> tag from an inappropriate location outside the head and body tags to the appropriate location inside the body tags.
Motivation
The motivation behind these changes is to adhere to best practices outlined by the W3C standards for HTML documents. According to W3C recommendations, the type attribute for <script> tags is not necessary and its omission helps reduce redundancy and clutter in the HTML markup. Additionally, placing <script> tags outside the head and body does not comply with organization and adherence to the recommended structure of HTML documents.
Testing
These changes have been tested locally to ensure that they do not …
> Heatmap html : W3C standards

- apps/dev-workbench/workbench.css
- apps/dev-workbench/workbench.html
Summary
In this Pull Request, I have adjusted the responsiveness of the dropdown UI options on the Workbench HTML page to ensure better usability and visibility on mobile devices. The dropdown options are now optimized to adapt to different screen sizes, providing a seamless user experience across various devices.
Motivation
The motivation behind this Pull Request is to enhance the usability of the Workbench HTML page, particularly on mobile devices. By improving the responsiveness of the dropdown UI options, we aim to make it easier for users to interact with the page and access the desired features, ultimately improving overall user satisfaction and engagement.
Testing
I have tested this change extensively across different devices and screen sizes to ensure that the dropdown UI options …
> Adjusted  Workbench html page option dropdown UI responsiveness on mobile view "

- .github/test.yml
- package-lock.json
- package.json
- test/paths.test.js
Motivation
I created this pull request to implement Jest testing for the application's path JS file. Automated testing helps ensure the reliability and correctness of the codebase by automatically verifying the behavior of these functions.
These tests were run locally using Jest to ensure the functionality of the classes. Additionally, the tests were integrated into the CI/CD pipeline using GitHub Actions workflows to ensure consistent and reliable testing across different environments.
> Test functions and automated git workflows testing for PathJS

- apps/dev-workbench/workbench.html
This PR fixes #983 
This PR fixes #982
> changed <a> tag to <button>

- apps/landing/landing.html
> added aria-label to "more" buttons

- apps/landing/landing.html
> Fixed issue #968 

- apps/table.html
> Improved step 3 in steps for uploading

- apps/signup/signup.js
> Improved email validation error message

- apps/table.html
- common/util.js
> Fixed unresolved color contrast issues on slides page

- apps/dev-workbench/workbench.html
- apps/dev-workbench/workbench.js
> Added Enter key support for back button navigation

- apps/batchloader/batchloader.html
- apps/dicom-connect/table.html
- apps/heatmap/heatmap.html
- apps/labeling/labeling.html
- apps/mini/viewer.html
- apps/model/model.html
- apps/segment/segment.html
- apps/viewer/viewer.html
> Enabled zooming on slides page

- apps/common.css
> Fixed inconsistent styling in footer

- apps/port/export.html
Closes https://github.com/camicroscope/caMicroscope/issues/1034
Element is having low color contrast issue, I have made necessary modifications with font style to meet sufficient color contrast.
> Fixed sufficient color contrast
