camicroscope/caMicroscope

apps/segment/segment.js
When the object count is zero in segmentation app and we click on download CSV we get a CSV file like 
i.e we get a blank CSV file. 
To avoid this. I added an JavaScript alert call immediately returned from the function downloadCSV without saving it.
Alert box
=> Alert when no data to save.

apps/viewer/uicallbacks.js
The notes oerflows and gos out of the popuppanel. This will prevent it from overflow. I have inserted new lines when they go out of popuppanel.
This  used to happen 
Now it will not go out of the popuppanel
=> Prevent popuppanel overflow

apps/viewer/init.js, docs/README.md
The shortkeys work fine for nanoborb. But for the browsers it doesn't work. The browser shortcut keys overrides our shortcuts. 
e.g. ctrl + r is for refresh in chrome. So Instead of measurement the page refreshes.
=> prevent default for shortkeys

apps/table.html
While uploading new slide users are not notified if slide name is already taken. And multiple copies of same name exists. Due to this it creates bad user experience because 
later users will not know what work they have done in which slide by looking at name.
Multiple slides with same name
Now it will be validated just like empty slide name.
=> Validation for existing slide name

README.md, package-lock.json, package.json
The user after running ```npm install```, can run ```npm run lint``` to view all the ESLint errors at once
=> Added script to check for all linting errors, at once

apps/table.html
The  table for available slides is now mobile-responsive. 
Fixes #293 
Now, in small screens, the table is scrollable :
=> Made the data-table mobile-responsive 

apps/viewer/uicallbacks.js
Fixes [Issue-109](https://github.com/camicroscope/Distro/issues/109) of Distro repository.
Earlier on saving annotation with empty note, the following error was shown in the browser console -
```
draw-overlay:stop-drawing error:
stopDrawing @ openseadragon-canvas-draw-overlay.js:653
openseadragon-canvas-draw-overlay.js:654 TypeError: Cannot read property 'length' of undefined
at anno_callback (uicallbacks.js:1115)
at saveAnnotation (uicallbacks.js:1594)
at Object.stopDrawing [as handler] (uicallbacks.js:1642)
at eventsource.js:162
at $.CanvasDraw.raiseEvent (eventsource.js:184)
at $.CanvasDraw.stopDrawing (openseadragon-canvas-draw-overlay.js:650)
stopDrawing @ openseadragon-canvas-draw-overlay.js:654
uicallbacks.js:1115 Uncaught TypeError: Cannot read property 'length' of undefined
at …
```
=> Allow empty note when saving annotation

apps/table.html
To save the database and application from XSS attacks, sanitized the input. So user inputs are sanitized before sending to the database.
Currently, a user can put any script or html formatting in the slide name
=> fix sanitize user input

README.md
The icons have been taken from https://material.io/resources/icons/.
The preview of new readme.md can be viewed at my repository - https://github.com/cjchirag7/caMicroscope/tree/readme-icons#using-tools
I hope this will help users to easily get an idea of the functions of all the tools. :)
=> Added icons for tools to README.md [User guide enhancement]

README.md
The changes are made in accordance with the new Caracal repository set up.
=> Updated the 'Fast local changes' section in README.md [Developer guide enhancement]

apps/table.html
Prevent the error 'unexpected end of input' at response.json() in table.html.
Fixes #320 
Actually, this error was due to the fact that  'fetch' doesn't accept responses with empty body.
=> Added validation in checkUserPermissions() to handle empty response

apps/heatmap/init.js, apps/heatmap/uicallbacks.js, apps/viewer/uicallbacks.js, components/heatmapcontrol/heatmapcontrol.js, core/extension/osd-heatmap-overlay.js
Fixes #307 
To store the colors , provenance.analysis.setting will have a new field 'colors'
- When mode is 'binal', length of colors is 1
- When mode is 'gradient', length of colors is >=2
The query which was earlier something like -
```
{"provenance.analysis.fields":[{"name":"necrosis","range":[0,1],"value":[0,1]},{"name":"tumor","range":[0,10],"value":[0,10]}],"provenance.analysis.setting":{"mode":"gradient","field":"necrosis"}}
```
is modified to -
```
{"provenance.analysis.fields":[{"name":"necrosis","range":[0,1],"value":[0,1]},{"name":"tumor","range":[0,10],"value":[0,10]}],"provenance.analysis.setting":{"mode":"gradient","field":"necrosis",colors":["#F23112","#553172","#333117" ] }}
```
In case, when mode is 'binal', the value of `color[0]` is the selected color .
=> Store gradient/color information in DB [ Fixes #307 ]

apps/loader/chunked_upload.js, apps/table.html
1. The Slide Upload form is slightly redesigned to match the application.
2. Now, the upload button will only be visible to the user who has the permission to upload a slide.(Using `what can i do` route)
Old:
New:
=> Upload form redesign and  upload button visibility

apps/model/model.js, apps/segment/segment.js
Makes #318 working. 
Though, #318 says it fixes segmentation app but code works on predict app. Both the apps have same problem so, fixed both of them.
=> fix duplicate model name

apps/model/model.js
Update the tfjs sample model link to https://github.com/camicroscope/tfjs-models as this repo has been added a few days back.
=> Update tfjs-model link

apps/viewer/init.js
Annotation popup shows the measurement unit as μm^2, now it will show it as μm².
=> fix measurement unit

apps/loader/chunked_upload.js, apps/loader/loader.js, apps/table.css, apps/table.html
Closes #326 
This includes the following changes :
- Refactored loader code to support only a single file upload, at a time
- Cursor has been made :point_up_2: when users hovers over the 'choose file' (browse) button in the modal
- The resetUploadForm() has been modified, in accordance with #325 
- The upload modal width is increased
After increased width, the modal look like this, on an average PC -
=> Clean loader code and increase upload modal width

apps/table.html
I have made the fix such that, it adds the DOM element $('datatables) , when it doesn't exist, which was the major cause of this problem.
**Screencast of the working**
=> Fix initialise() on first slide upload

apps/viewer/uicallbacks.js
After hiding a segment popup still used to stick on the screen.
After this fix the popup will close as soon as the corresponding segment hides.
=> fix popup close on hidden segment

apps/loader/chunked_upload.js, apps/table.html
Closes #343 
Added the following features
- Convert spaces (' ') to underscores('_') on 'change' event in FileName.
- Validate the extension on 'change' event in FileName and display error message, appropriately
**Screencast**
=> Convert space to underscore and validate extension, on change of filename

apps/table.css, apps/table.html
Closes #355 
I have made the following changes 
- Improved the implementation of search, so that it works perfectly and pagination is also taken care
- Changed the search placeholder, to include a search icon
A screencast of the working -
=> Made search working and placed search icon [Fixes #355]

apps/loader/chunked_upload.js, apps/table.html
An option to upload the slide image from URL has been added. 
This feature works with [SildeLoader #28](https://github.com/camicroscope/SlideLoader/pull/28)
Note that the speed of upload depends on both the source and the destination.
=> "Upload from URL" option in the upload form

apps/table.css, apps/table.html
Fixes #357 
The following changes have been made :
- Modified the comparator function to return -1, +1 or 0, depending upon the comparison of the elements
- If the values can be converted to number, then they would be first converted to number, and then the comparison would occur. Currently, the comparison, was done, taking them all, as strings, in lexicographical order. But there might be some cases like :   '2' > '12' (lexicographically)  but 2 < 12 (numerically) , which may produce undesired results to the user.
- Made the cursor to a :point_up_2: , when user hovers over the up/down button 
- Increased the size of up and down buttons from 10px to 15px, so that they are visible
- Now, the sort works perfectly, in both Chrome and Firefox
=> Improved sorting of datatables [Fixes #357]

apps/model/model.js, apps/segment/segment.js
The check duplicate name feature was added in #318 and was fixed in #327 . But the bug was again added in #348 as some of the old code was added back. This PR fixes the bug .
Also earlier the feature worked only after refreshing the table as the ``` modelName ``` was only updated during initialization which meant same name model could be uploaded in the same session. This has also been fixed .
=> Model upload bug

apps/model/model.css, apps/model/model.js, apps/segment/segment.css, apps/segment/segment.js, package-lock.json
Fixes #361 
It was caused as all the ``` delete model ``` buttons were being assigned the same id . So when one was clicked all of them were triggered. 
This PR also makes the ``` check duplicate name ``` feature compatible with the ``` delete ``` feature . Earlier even after deleting the model, that name couldn't be used again. Now it when the model is deleted the name is also deleted and can be reused .
=> Delete model bug

apps/viewer/uicallbacks.js, apps/viewer/viewer.html, core/CaMic.js, core/StatesHelper.js, core/openseadragon-rotation.css, core/openseadragon-rotation.js
This is an **initial implementation** of the rotation bar of OpenSeadragon instance.
**Current Behaviour**
Currently rotation is enabled only if none of the tools ( measurement tool, draw annotations etc. ) are not selected.
Upon selecting any tool rotation is disabled and image angle is set to 0 degrees again.
This is done because there are issues with the tools when image is rotated.
Maybe we can open separate issues for resolving these problems.
=> Implementation of Rotation Bar

apps/table.css, apps/table.html, core/Store.js
Slide name can be updated by the user who have the proper permissions.
=> Slide name change functionality  &  direct slide delete in No-Security Mode

apps/Info.html, apps/info.css, apps/landing/landing.html
The following changes have been made in information dashboard :
- Implemented searching
- Implemented sorting
- Improved the view of the table and made it responsive
- Removed unnecessary code like sanitize(), validateForm() functions which are not needed in information dashboard
- Included the 'Info' option in navbar in the landing.html page (which was missing earlier)
- Fixes camicroscope/Distro#95
- Also, earlier the dashboard table was occupying only a small part of the screen, as the footer had an absolute position. This has been fixed now.
- I have tested these features in both Chrome and Firefox, in desktop as well as mobile view.
=> Implemented searching and sorting in Information dashboard

apps/loader/loader.js, apps/table.css, apps/table.html, css/popup.css
The following changes have been made :
- Re-initialized slides table on slide name update
- Replaced alert by a popup for UI  improvements, when slide update is successful
- Replaced alert by a popup for UI  improvements, when slide delete is successful
- Made a function for showing popup for a success message and call it at other places, to prevent using the same piece of code again and again
- Made position of popup as 'fixed' for better UI
- Replace alert by inline error message in form-input, when user enters duplicate value of slide name for UI enhancement
- Fixes #373 
- Earlier the function initialise was called outside of the promise, wrongly. This resulted in no initialisation of the slides table occurring, after the name …
=> Re-initialize slides table on slide name change and show popup when successful

apps/table.html
The following changes have been made in sorting approach for slides page, to keep it a lot similar to that of the information-dashboard page 
- The 2 separate icons for up and down arrow are replaced by a single icon for sorting
- The information for index and order is stored in data-* attributes of the span tag, so as to simplify the code for sorting and making it more understandable 
- Earlier, there were 2 separate icons for sorting which was not creating a good user experience
- The code for sorting earlier used to store the title in some part of the id, then extract it using substr() function and then match it with available headings to find out the index of the column, increasing the complexity and decreasing the readability of the code.  
- Tested in both Chrome and Firefox
=> Simplified sorting in slides page

apps/model/model.css, apps/model/model.js, apps/segment/segment.html, apps/segment/segment.js
In model app:
- After changing class list, instead of an alert a popup is shown.
- UI of class change button
In segment app
- After uploading model, a popup is shown.
- After deleting model, instead of an alert a popup is shown.
Improves User Interface
Tested in Chrome and Firefox
=> [Enhancement] Popup display in model and segment app

apps/model/model.js, apps/segment/segment.js, apps/viewer/uicallbacks.js
Toast for no heatmap data instead of alert
Toast for no markup on annotation instead of alert
Documented functions inside viewer uicallbacks.js
- segment.js and model.js
Changed name while deleting model to avoid confusion which was created in #382 and #375  
- Documenting code is good for fast development. 
- Replacing alerts with toasts to improve UX
=> [Enhancement] replace alerts to toasts in viewer

apps/batchloader/batchLoader.js, apps/batchloader/batchloader.html, apps/table.css, apps/table.html
- A new batch slide loader app page has been created at `/apps/batchloader/` to upload multiple files simultaneously with ease.
- Slide name can be generated by the user provided name eg. `sample_1`,`sample_2` etc.
- File names can either be set to default (original file names) or can be generated similar to the slide name.
- This is an initial implementation and I look forward to suggestions and feedback.
- Working on better implementation of validation and error handling.
- Some functions in `batchLoader.js` are modified from `chunked_loader.js` and `loader.js` to behave accordingly since I was trying to solve the issue without making changes in slideLoader(at least for now).
- In reference to #352 
- Tested on Mozilla 75.0, …
=> Initial Implementation of batch slide loader

apps/batchloader/batchLoader.js, apps/batchloader/batchloader.html, apps/table.html
Some features are added to the batch loader:
- Delete Functionality to remove the slide.
- Individual Slidename and FIlename change functionality.
- `Info` icon is added which to every row which on click describes various information about the slide like `original filename`, `filename` , `slide name`, `status`, `token` etc.
- Filename/slidename validation during individual edit.
- Improving BatchLoader and working in reference to #352.
Tested on: 
- Mozilla 75.0, Chrome 81.0
- Ubuntu 19.10
=> Batch Loader Enhancement 

apps/Info.html, apps/loader/chunked_upload.js, apps/table.html, common/util.js
Following changes have been made
- Add filter UI in slide table and information dashboard
- Validate filter when user uploads a slide.
- Simplify code for searching in both table.html and info.html
- Made sure that searching, sorting and filtering, all work together without any collision.
- The filters are shown only in security mode.
- Fixes #386 
- Tested both desktop and mobile view in Chrome and Firefox by once login in as 'Admin', once as 'Editor' with some filters and once by setting `DISABLE_SEC` and `ALLOW_PUBLIC` as true
1. Filters UI in table.html (Similar exists in Info.html)
2. Validation for filter during Slide Upload
=> Add filter UI in slide table and information dashboard [Feature]

README.md, apps/viewer/init.js, apps/viewer/tut.js, apps/viewer/uicallbacks.js, apps/viewer/viewer.html
Following changes have been made:
- Added download tool inside the slide viewer.
- Added download icon to README.md
- Added download icon to the bootstrap tour guide.
- This was marked as a 'to-do' in the uicallbacks.js file.
- Tested in Google Chrome and Firefox
=> Added download button in slide viewer [Enhancement]

README.md, apps/table.js, apps/viewer/init.js, core/Store.js
Add @nanli-emory's  work from custom/check into the platform proper. It's been a very useful tool across many projects. 
Closes #406 
Simple test of marking reviewed and checking table.
=> Review Status Workflow and Indicators

apps/model/model.css, apps/model/model.js, apps/segment/segment.css, apps/segment/segment.html, apps/segment/segment.js
- Initial roi feature in the segment app .
- Feature to extract roi from selected region
Other small changes :
- Added progress percentage in snackbar
- Typo fix
- Use innerText instead of innerHTML
OS : Ubuntu 20.04
Browser : Firefox
=> Initial roi feature in segment app 

apps/model/model.css, apps/model/model.js, apps/segment/segment.js
- Added feature to give user choice to use  SlideLoader to download the patches
- Updated the download folder structure so that now each class is downloaded in a separate folder with the class name
- To make roi feature usable with large slide 
- In many places , datasets divided into folders according to their classes is used directly 
Ubuntu 20.04
Firefox 
This depends on [SlideLoader #34 ](https://github.com/camicroscope/SlideLoader/pull/34)
=> Use backend to download and update download folder structure

core/extension/openseadragon-canvas-draw-overlay.js
Re "FAST" Meeting; use localstorage to check if we've warned the user about polygons before. Still do a console info in case someone later wonders why the area/perimeter fails.
=> warn just once about self-intersecting polygons

apps/loader/chunked_upload.js, apps/table.html, docs/cloudUploadAPIs.md
This works with [SlideLoader #40](https://github.com/camicroscope/SlideLoader/pull/40) and [Distro #154](https://github.com/camicroscope/Distro/pull/154)
- An "**upload from google drive**" icon is provided during the upload process.
- Google Picker API is used to let user choose a file from their google drive storage.
- The picker api will extract the fileID from the chosen file and it'll be sent to Slideloader where Google Drive API will download the corresponding file directly on server-side saving user's time and data.
- The instructions for the API usage is described in `docs/cloudUploadAPIs.md`
- **Browser**: Firefox (v83), Chromium (v87)
- **OS**: Windows 10, Arch KDE (Linux-LTS)
**NOTE**:
- The authentication has to be done twice, once for picker api and another time for drive …
=> Upload from Google Drive [Feature]

.eslintrc.js, package-lock.json
The issue #469 is solved here. It relates to solving linting error in the code. 
- The `linebreak-style:0` rule has been added to the rules in the `eslintrc.js` file.
- Issue: #469 
**Please describe in detail how you tested your changes.
- Environment details: 
* OS: Windows 10
* Terminal: Windows Powershell, Hyper(by Microsoft)
- Resources used to solve the issue: Suggestion by @birm in comments of the #469 issue and eslint docs.
=> Lint error

apps/table.html
This PR adds responsiveness and fixes UI issues in the table.html page.  
- This solves issue #476 
- The responsiveness and consistency in the codebase is required and henceforth making it easy to add new functionalities in the project.
**This has been tested by resizing window and running the application in different browser environments as well. This is a UI fix, so expecting that this much testing is enough.
The below snapshots are after fix.
* Duplicates removed.  
* Add responsiveness.
**(If you're unsure about any of these, don't hesitate to ask. We're here …
=> UI responsive

google_login.html
**Describe your changes in detail
The code documentation for google login is improved. Meaning of each variable is defined clearly.
=> Improved the Documentation  #413

apps/viewer/tut.js
Solves #481 
It is a UX improvement in tour.
What this change does?
- The tour that is provided for ease for users to understand if left in between, continues from where the user left i.e. default.
- But generally by UX perspective, the tour must start from the beginning because of the following problems:
* If the tour is left at the end, it resumes from the end and doesn't again point to start.
* If the user closes the window and when opens again, the local storage has stored the value of last left tour element. And thus will resume from there itself; which is unexpected for user as User would expect it to be from beginning only.
**Please describe in detail how you tested your changes.
- It changes `tut.js` file. It has been tested for its working on local set up.
**What types of changes …
=> improve tour resume UX

HISTORY.md, README.md, apps/viewer/init.js, apps/viewer/tut.js, apps/viewer/uicallbacks.js
**Describe your changes in detail
This screenshot feature helps user to take screenshot of the slide along with annotations and download it as an image.
*Why is this change required? What problem does it solve?
This is useful as screenshots of slides are required by several users as they need to be included in reports or research papers.
Note :
This is the first and basic version of screen capture. Next step in this includes adding functionality to capture only a selected area of the slide.
This is the same PR as #493 
**Please describe in detail how you tested your changes.
I tested it on my local setup
**(If you're …
=> [New Feature] Screenshot of Slide

components/simplecontextmenu/simplecontextmenu.css, components/simplecontextmenu/simplecontextmenu.js, core/CaMic.js
- Added undo feature to draw tool, works well for Draw-Infinity-mode. Added it in the simple-context-menu. I don't think it breaks anything
Previously only clear-all option was present, which required to erase all shapes to remove a single one. 
Code was already available in OpenSeadragon api
It works well, I could save the annotations
=> Add undo feature in Draw tool

apps/signup/signup.js
** Regex validation for email in the signup form. The program throws an alert and doesn't proceed to registration.
** During user registration, it is possible currently to sign up with an invalid email. I felt adding an email validation with a tried and  tested regular expression so the form doesn't accept invalid email might be a good addition.
** The regex is based on RFC822 standard, so it covers the entire spectrum of email addresses. I have used the regex from w3resources. So it is expected to work right.
I tested the same code with camicroscope. It works for all the cases. I have used the same code in my earlier projects and it has never caused an issue.
=> Regex validation for email during signup process

apps/viewer/init.js
Feature for additional links in toolbar of viewer.
This change provides the ability to put additional links in the toolbar for the slide viewer. This PR should solve #468 . This feature also needs a JSON file which is described in [Distro PR-161](https://github.com/camicroscope/Distro/pull/161).
The new links are appended as shown with the green marker.
The links are customizable with the following parameters:
1. The URL
2. The name to be displayed
3. The icon to be displayed (material icons)
4. A boolean to choose if the link is to be opened in new tab, or in current tab.
Yes it fixes #468 
This has been tested on local system running Ubuntu 18.04, docker-compose version 1.28.6, and Mozilla firefox browser.
=> Feature for additional links in toolbar

common/util.js
In this Pull Request I have added support for including rulers in the Screenshot feature as well. This is in continuation to the pull request #496 
Currently, rulers are not included in the screenshot. I implemented it without using any eternal library thus, not affecting the performance much.
I have attached the screenshot of the working of the feature
=> Support for including Measurements in the ScreenShot added

apps/Info.html, apps/dev-workbench/workbench.css, apps/dev-workbench/workbench.html, apps/info.css, apps/table.css, apps/table.html
Issue: #517 
I have updated the bootstrap versions in workbench.html, info.html, table.html files.
=> Update bootstrap in table.html, workbench.html and info.html

apps/segment/segment.html, apps/segment/segment.js, apps/segment/segmentpanel/segmentpanel.css, apps/segment/segmentpanel/segmentpanel.js, apps/table.html, apps/table.js, apps/viewer/init.js, apps/viewer/uicallbacks.js, apps/viewer/viewer.html, common/smartpen/autoalign.css, common/smartpen/autoalign.js, common/util.js, components/layersviewer/layersviewer.js, core/Store.js, core/extension/openseadragon-canvas-draw-overlay.js, core/extension/segment-annotation.js
Segmentation extension
- Converted Segmentation results to annotations using contours and saved it for future use.
- Fixed slide renaming (slidechangemodal wasn't working earlier)
- Hopefully fixed the bug in moving-points (multi-mode) and also fixed canvas bugs in segmentation.
- Trivial UI changes
Saving segmentation as annotations could be useful, as it can be used in future, and also could circle interesting areas as labels. Could also save whole image instead of contours as overlays but intentionally left it.  
I have added segmentation overlays which could be used both in viewer, side-by-side viewer and segmentation tabs. Currently, it can store name, notes and deletion can be done using popup-panel.
=> Include segmentation as annotations

apps/table.html
Fixed UI on table.html page, added margin between search bar and dropdown menu
before: 
after:
While doing code refactoring, I noticed that there was no margin between the mentioned two components. 
This does not affect any functionality.
I was thinking about doing more such changes to improve the UI. If that's okay, please assign me the task.
=> fix ui: added margin between dropdown and search bar

apps/table.html, package-lock.json
On the slide page, The reload button is not responsive. The button's right edges are cut into small devices. It also makes less Ui. so I fixed the issue.
=> The Reload button is not Responsive for small size devices

apps/dev-workbench/workbench.css, apps/dev-workbench/workbench.html
fixed the overall styling inside workbench section and made it consistent and responsive for all screens
I have opened a issue on #605
**Behavior after fixed**
https://user-images.githubusercontent.com/76092296/225430485-73ad07e6-e504-4af2-8cbd-73c5d8a7c9d2.mp4
**Behavior before fixed**
=> fix: :bug: Responsiveness issues of workbench section #605

apps/signup/signup.html
**Summary**
I have added a footer to the sign-up page for improved user experience.
Below are some screenshots
Before
After
**Motivation**
This Pull Request is motivated by the need to make the website consistent with the application's design. All other pages contain the footer.
**Testing**
I have tested it on different devices and screen sizes to ensure it is fully responsive.
**Questions**
Shall the footer be added to the home page too? Are there any links that are to be attached to the footer? Are there any additional changes or improvements that could be made?
=> Adding Footer to Sign Up Page

apps/landing/main.css
Issue [#633](https://github.com/camicroscope/caMicroscope/issues/633#issue-1647431367) Solved
**Summary**
I have added a customized scrollbar to the application for improved user experience. The scrollbar is visually appealing and intuitive, matching the overall design of the application. 
**Motivation**
This Pull Request is motivated by the need to improve the design and user experience of the application. The default scrollbar in the application is functional but does not match the overall design aesthetic. The customized scrollbar addresses these design issues and provides a more visually appealing and intuitive scrollbar that is consistent with the application's design.
**Testing**
The scrollbar has been designed to be visually appealing and functional across different devices and …
=> Custom Scrollbar for Improved User Experience

apps/dev-workbench/workbench.html, apps/landing/landing.html
Fixed issue number: #615 
Thank you. 
Do let me know if there are any changes required.
=> FIXED Overlapping / Not properly styled on class=card in the workbench.html

apps/batchloader/batchLoader.js, apps/batchloader/batchloader.html, apps/table.js
Subpullrequests: https://github.com/camicroscope/SlideLoader/pull/68 https://github.com/camicroscope/iipImage/pull/17
1) Allow `.dcm` extension
2) Use `caMicroscope/image-decoders`, our new repo, as the base Dockerfile that builds OpenSlide. If needed, `FROM camicroscope/image-decoders` can replaced with `apt-get install libopenslide0`.
Before merging, Tony and Nan don't have access to caMicroscope Docker so @birm could you please publish an image of currnet https://github.com/camicroscope/image-decoders to Docker Hub so that we can change the images to be downloaded from camicroscope rather than currently my repo for easy testing.
caMicroscope.yml for testing my three pullrequests:
```
version: '3'
services:
mongo:
image: mongo:4.2-bionic
container_name: ca-mongo
restart: always
logging: …
```
=> DICOM files

apps/batchloader/batchLoader.js, apps/loader/chunked_upload.js
Currently, when a user tries to upload a filename such as “slide(1).svs”, Slideloader will save it as “slide1.svs” and tell the frontend about this. This happens when finalizing an upload. However the frontend discards this information and after finalizing, validates by calling the metadata API of “slide(1).svs”, which returns “Not found”, and the user never reaches the “success” stage.
Firstly, the frontend should display the sanitized filename on upload finalization, and use this filename for validation.
Secondly, the frontend should also replace the filename with the sanitized one when starting upload.
Doing these both will give us good UX so that we won’t need to list: “the filename cannot contain (,), … etc”, but the user’s entered input will have these removed automatically and the …
=> Handle uploading filenames with special characters

apps/table.html, apps/table.js
Sorry, I forgot that I didn't open a pull request for this
Adds a dicom button to the table menu which fetches the port and ip from slideloader
In addition, fixes a case about handling filepaths to files in subdirs. These happen because we take "filename" from database or "location" from database and trim from the last slash. Instead we should use filepath from database whenever possible (Ryan, please remember this description so that if in the future you encounter any problems with files in subfolders, this is the cause and the fix)
=> Dicom button

apps/heatmap/init.js, apps/labeling/labeling.js, apps/mini/init.js, apps/model/model.js, apps/segment/segment.js, apps/viewer/init.js
It used to stay stuck loading on a failure of the tile server forever, now it gives some info.
Before:
After:
=> Show tileserver errors as usual redirect

apps/dev-workbench/workbench.html, apps/dev-workbench/workbench.js
This Pull Request addresses the issue that was causing the ML kit help-guide to malfunction. The root cause was an improper usage of the ‘marked’ library, which is responsible for parsing Markdown into HTML.
Changed files :: `apps/dev-workbench/workbench.js` and `apps/dev-workbench/workbench.html`.
Before changes ::
https://github.com/camicroscope/caMicroscope/assets/124369508/f1a304a1-0860-4b3f-9f3e-5ec7d10f773f
After changes ::
https://github.com/camicroscope/caMicroscope/assets/124369508/6ea40b47-8787-4131-9172-ee00a213f915
=> Fixes #606 : This Pull Request resolves the bug that was preventing the ML kit help-guide from functioning properly.

apps/signup/signup.css
The expected behavior was that there should be a noticeable gap between these elements to enhance user experience and readability. After investigating the issue, I successfully implemented the requested style change, ensuring the desired gap between the SignUp and Feedback Button.
this change  will enhance user experience and readability
Yes, I have executed the test using the commands and tests that Is outlined in the repository. and executed with out any errors
I'm sure about everything but this is a style change i took the gaping between the buttons with my own assumption we can make the gap more or less depending on the requirements
=> (#699)-the SignUp and Feedback buttons overlapping fixed

apps/port/export.html
The implemented feature adds a "Go Back" button link to our web application. When users click this button, they will be redirected to the previous page they were on.
before
after
https://github.com/camicroscope/caMicroscope/assets/108942025/91ec9bda-870b-4053-a081-4664e52eaff0
The motivation behind implementing this feature was that, at first glance, after I have visited the export page, I noticed that I needed to copy the id, and so I thought we could add a back feature where I will go back and grab the id. Users often expect a way to easily return to the previous page, especially in our case when someone hasn't copied the id or maybe wants to go back and copy more.
I have added a new button element with appropriate styling (using bootstrap) and labeled it "Go Back."
In the button's …
=> Enhanced navigation with a ‘Go Back’ Button feature on export page.

apps/Info.html
Fixed disabled in mobile view #830
Remove the user-scalable="no" parameter from the content attribute to allow zooming.
Add  maximum-scale=2.0 for ensuring that the maximum-scale parameter is not less than 2 to allow sufficient zooming.
By removing the user-scalable="no" parameter and ensuring the maximum-scale parameter is set appropriately, users will be able to zoom in and out on the Info Page in mobile view, improving accessibility for people with low vision.
I'm passionate about contributing to the caMicroscope organization to further my skills and knowledge. One of the issues I've successfully fixed is #830, which involved addressing the disabled zooming on the mobile view of the Info Page. I would appreciate a review of my work to ensure it meets the project's standards. This …
=> Fixed disabled in mobile view #830

apps/Info.html, apps/heatmap/heatmap.html, apps/labeling/labeling.html, apps/model/model.html, apps/multi/multi.html, apps/port/export.html, apps/port/import.html, apps/redir.html, apps/segment/segment.html, apps/signup/signup.html, apps/table.html, apps/viewer/viewer.html, index.html
Fixed issue #837 
HTML element does not have Lang attribute #837 
To fix this issue, I added the `lang` attribute to the `html` element and specify the appropriate language code that reflects the primary language of the content on the page. For example, for English content, I would use `lang="en"` in the `html` tag.
I'm passionate about contributing to the caMicroscope organization to further my skills and knowledge. One of the issues I've successfully fixed is [Accessibility] HTML element does not have lang attribute #837. I would appreciate a review of my work to ensure it meets the project's standards. This experience has deepened my understanding of user-centered design and my ability to create intuitive user interfaces.
=> Fixed issue #837  HTML element does not have lang attribute 

apps/viewer/init.js
Added X, Y (image coordinate ）and zoom to the pop-panel
Because until now, it was not possible to check the image coordinate and zooming information of the area annotated in mouse mode.
Before
After
please check whether my PR matches your issue #844 or not.
=> Saving Marks Should Include User's X, Y, Zoom, etc #844

apps/landing/landing.html
I added aria labels to the images (which also happen to be links) on the home page. Those images didn't initially have aria labels which posed an accessibility issue for users who use only keyboards to navigate the site.
This PR fixed #901
=> Added Aria Labels to Image Links

apps/signup/signup.html, apps/table.html
Removed the user-scalable="no" parameter from the content attribute to allow zooming.
Add maximum-scale=2.0 to allow sufficient zooming.
This PR fixes #830
=> Fixed disabled zooming in mobile view

apps/model/model.html
Summary
I made the following changes to improve compliance with W3C standards:
Removed the unnecessary type attribute from <script> tags.
Moved two <script> tag from an inappropriate location outside the head and body tags to the appropriate location inside the body tags.
Motivation
The motivation behind these changes is to adhere to best practices outlined by the W3C standards for HTML documents. According to W3C recommendations, the type attribute for <script> tags is not necessary and its omission helps reduce redundancy and clutter in the HTML markup. Additionally, placing <script> tags outside the head and body does not comply with organization and adherence to the recommended structure of HTML documents.
Testing
These changes have been tested locally to ensure that they do not …
=> Model html  upated to  W3C standards

apps/Info.html
I have resolved the overflow issue in cards, applied Bootstrap styling, improved performance by moving scripts, and conducted code cleanup.
before
The motivation behind this was to address UI overflow problem, enhance styling consistency, optimize page load performance, and improve code maintainability.
https://github.com/camicroscope/caMicroscope/assets/108942025/a9fe1434-b1aa-473f-9834-74119ff2d692
I have tested for responsive behavior and script execution, ensuring no adverse effects on performance.
None.
=> Resolve overflow issue, apply Bootstrap styling, optimize performance, and clean up code

apps/labeling/labeling.html
Summary
I made the following changes to improve compliance with W3C standards:
Removed the unnecessary type attribute from <script> tags.
Moved a <script> tag from an inappropriate location outside the head and body tags to the appropriate location inside the body tags.
Motivation
The motivation behind these changes is to adhere to best practices outlined by the W3C standards for HTML documents. According to W3C recommendations, the type attribute for <script> tags is not necessary and its omission helps reduce redundancy and clutter in the HTML markup. Additionally, placing <script> tags outside the head and body does not comply with organization and adherence to the recommended structure of HTML documents.
Testing
These changes have been tested locally to ensure that they do not …
=> Labelling html updated to W3C standards

apps/viewer/init.js
Reverts camicroscope/caMicroscope#902
Does not work as described, returns the current view x, y, zoom, which is not useful
=> Revert "Saving Marks Should Include User's X, Y, Zoom, etc #844"

apps/viewer/init.js
Reverts camicroscope/caMicroscope#942 which reverted #902 
Apparently we're indecisive here. Making this for deeper test/review
=> Revert "Revert "Saving Marks Should Include User's X, Y, Zoom, etc #844""

.github/test.yml, common/DrawHelper.js, package-lock.json, package.json, test/DrawHelper.test.js
Summary
I wrote test functions in the test file for the drawLine and drawCircle methods of the caDrawHelper JS file. These tests verify that the methods correctly call the appropriate canvas methods to draw lines and circles, respectively.
Motivation
The purpose of writing these test functions is to ensure the correctness and robustness of the caDrawHelper class. By having comprehensive test coverage, we can confidently make changes to the codebase, knowing that existing functionality remains intact.
Testing
The test functions have been carefully crafted to cover various scenarios and edge cases for drawing lines and circles. They validate the behavior of the methods and provide assurance that they perform as expected.
=> Jest test for DrawerHelper JS

.github/workflows/axe-a11y-check.yml
On https://github.com/camicroscope/caMicroscope/actions/runs/9519258356/job/26242052785#step:8:22 noticed error ` Run npm install -g @axe-core/cli
added 84 packages in 5s
2 packages are looking for funding
run `npm fund` for details
Running axe-core 4.9.1 in chrome-headless
Error: session not created: This version of ChromeDriver only supports Chrome version 126
Current browser version is 125.0.6422.141 with binary path /opt/google/chrome/chrome
Please install a matching version of ChromeDriver and run axe with the --chromedriver-path option:
$ npm install -g chromedriver@<version>
$ axe --chromedriver-path $(npm root -g)/chromedriver/bin/chromedriver <url...>
(where <version> is the first number of the "current browser version" reported above.)
Error: Process completed with exit code 2.` …
=> add chrome driver@125 explicitly.

apps/table.js
This PR fixes  #969
I added an arial-label to the delete and download buttons to be recognized in the screen readers.
=> I added aria-label to the buttons

apps/Info.html, apps/common.css, apps/info.css, apps/table.html
=> Fixed color contrast issues on slides and info pages

apps/viewer/init.js, components/toolbar/toolbar.js
=> Added aria-label to toolbar icons

apps/dev-workbench/workbench.css, apps/dev-workbench/workbench.html
=> Fixed keyboard accessibility issues on Workbench page

common/pureform/pure-form.js
This PR resolves this  #1002
The part of the code where it says that the field must be a value has been changed, the change now makes it clearer to the user what the expected format is for that field
=> Fixed the Name Suggestion error on the Slide Viewer Page

apps/table.html
This PR fixes #1019. The issue persisted even after aria-label was added to the select element (in PR #1021 that has been merged). In this PR, I changed the aria-label to a title attribute.
=> Added title to select element

apps/dev-workbench/workbench.css, apps/dev-workbench/workbench.js
=> Fixed keyboard accessibility issue on workbench page

apps/Info.html, apps/dev-workbench/workbench.html, apps/landing/landing.html, apps/table.html
=> Added skip-to-content link

apps/table.js
This pull request addresses an issue where the `.stacktable` components (`stacktable.small-only` and `stacktable.large-only`) were being activated simultaneously on screen sizes below 800px, causing table duplication. Additionally, it ensures that the `stacktable()` function is called only once after all table content has been fully updated to avoid redundancy or conflicts.
The issue arises from calling the `stacktable()` function multiple times when the table content changes (e.g., when pagination is applied, or the number of table entries is updated). This results in a table duplication issue when both the `.stacktable.small-only` and `.stacktable.large-only `classes are triggered at the same time on smaller screens. The goal is to ensure proper handling of table initialization and …
=> fixes #1009 : table duplication issue when screen size less than 800px

apps/labeling/downloadTable.html, apps/managment/editUser.html, apps/managment/editUser.js
* preview button
* allow it to have a download collection zip url
* download as separate user type
=> Update download role for HTT

components/sidemenu/sidemenu.js, components/toolbar/toolbar.css, components/toolbar/toolbar.js, css/style.css
* Add camic logo in place of the apps icon
* Increase icon size from 24 to 36, unless the screen is less than 750px wide. Keep height 36 so they're easier to touch.
Large icons:
Small icons:
* Fix drop down spacing so that they're reasonably possible to select
Before: 
After:
=> Toolbar Usability + Logo

apps/table.html
- **Layout Fix**: Wrapped the Google Drive, "Upload from URL", and "Upload from Local" links in a flexbox (`display: flex; align-items: center; justify-content: space-between;`) and removed the absolute positioning to resolve the issue.
=> [FIX]: Add visual focus indicator to 'Upload from URL' and 'Upload from local' links (#1018)

components/ml-assistant/ml-assistant.js
- **`interactive: true`**: Keeps the tooltip open when hovering over the tooltip itself, so it doesn't disappear immediately. This fixes the issue where the tooltip would disappear before users can interact with it.
- **`trigger: 'mouseenter focus'`**: Ensures the tooltip activates on both mouse hover and keyboard focus, making it accessible for keyboard users and screen readers.
- **`aria` configuration**: Setting `aria: { content: 'describedby' }` links the tooltip to the label for screen readers, providing a description of the label's purpose.
This configuration help ensure tooltip remains visible when needed and is fully accessible for all users, including those who rely on screen readers.
=> [FIX] Tooltip Inaccessible on Hover in Annotation Assistant (#994)

apps/port/import.html, apps/port/xml2geo.js
=> Fix port xml

common/DrawHelper.js, core/extension/openseadragon-overlays-manage.js
=> Default color/style

apps/model/model.css, apps/model/model.js
This pull request modifies the CSS styles for the info modal to create a responsive layout that adapts to different window sizes. This ensures the modal content, particularly the table headers ("Name," "Classes," etc.), displays properly on desktop and mobile devices.
Motivation:
The previous info modal layout caused table headers to overflow on mobile devices, potentially hindering readability and user experience. This change addresses that issue by making the modal responsive, allowing headers to stack vertically on smaller screens.
The changes have been tested thoroughly on various screen sizes (desktop, tablet, mobile) using browser developer tools to simulate different viewports.
Functionality of the info modal and its content remains intact across all tested screen sizes.
Before …
=> Info modal fixed for different window sizes

apps/dev-workbench/workbench.html
Remove duplicate "Choose file" buttons and consolidate functionality in Workbench UI
This PR removes redundant "Choose file" buttons across the Workbench UI, ensuring a cleaner and more intuitive design. A single "Choose file" button is now shared dynamically between the dataset selection and custom data upload sections. The UI has been refactored to avoid duplication while maintaining all required functionality.
Before:
Multiple "Choose file" buttons appeared across different sections and modals.
Confusion for users due to redundant UI elements.
After:
Only one "Choose file" button dynamically serves all use cases.
Simplified UI improves user experience and reduces visual clutter.
Screenshots:
Before: 
After: 
The previous design had multiple "Choose file" buttons that served the same …
=> Remove multiple buttons with same functionality in dev workbench
